name: Update WordPress with Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Changelog Version'
        required: true
        default: '1.0.0'

jobs:
  updateWordpress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install jq

    - name: Extract Specific Changelog Block
      run: |
        VERSION_HEADER="## [${{ github.event.inputs.version }}]"
        VERSION_HEADER_ESCAPED=$(printf '%s\n' "$VERSION_HEADER" | sed -e 's/[]\/$*.^[]/\\&/g')
        lines_under_version_header=$(awk "/$VERSION_HEADER_ESCAPED/"' {p=1; next} p && /^## \[/ {p=0} p' CHANGELOG.md)
        echo "$lines_under_version_header" > specific-changelog.md

    - name: Convert Extracted Changelog to JSON
      run: |
        jq -Rs '{title: "Changelog Update for Version ${{ github.event.inputs.version }}", content: .}' specific-changelog.md > changelog.json

    - name: Update WordPress
      env:
        WP_API_ENDPOINT: ${{ secrets.WP_API_ENDPOINT }}
        WP_API_TOKEN: ${{ secrets.WP_API_TOKEN }}
      run: |
        echo "Updating WordPress..."
        curl -X POST $WP_API_ENDPOINT \
             -H "Authorization: Bearer $WP_API_TOKEN" \
             -H "Content-Type: application/json" \
             --data @changelog.json
