name: Update WordPress with Changelog

on:
  workflow_dispatch:

jobs:
  updateWordpress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install jq

    - name: Extract Latest Changelog
      run: |
        sed -n '/<!-- Latest -->/,/<!-- \/Latest -->/p' CHANGELOG.md > latest-changelog.md

    - name: Convert Latest Changelog to JSON
      run: |
        jq -Rs '{title: "New Changelog Update", content: .}' latest-changelog.md > changelog.json

    - name: Update WordPress
      env:
        WP_API_ENDPOINT: ${{ secrets.WP_API_ENDPOINT }}
        WP_API_TOKEN: ${{ secrets.WP_API_TOKEN }}
      run: |
        echo "Updating WordPress..."
        curl -X POST $WP_API_ENDPOINT \
             -H "Authorization: Bearer $WP_API_TOKEN" \
             -H "Content-Type: application/json" \
             --data @changelog.json
