name: Gutenberg Market Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare plugin directory
        run: |
          # Creates a directory for the plugin with its version
          PLUGIN_DIR="roadmapwp-pro"
          mkdir -p release/$PLUGIN_DIR
          
          # Sync the project files to the PLUGIN_DIR, excluding unwanted files
          rsync -av --exclude={.git,.github,composer.json,composer.lock,package.json,package-lock.json,phpstan.neon,phpstan-baseline.neon,postcss.config.js,tailwind.config.js,EDD_Licensing.php,EDD_SL_Plugin_Updater.php,gutenberg-market.php} ./ release/$PLUGIN_DIR/
          echo "Prepared plugin directory with necessary files."

      - name: Zip the plugin folder
        run: |
          # Zip the PLUGIN_DIR, ensuring the path is directly in the workspace
          zip -r "${GITHUB_WORKSPACE}/roadmapwp-pro-${{ github.event.inputs.version }}.zip" "release/roadmapwp-pro"
          echo "Created zip file with the plugin in the workspace."

      - name: Upload the prepared zip file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: roadmapwp-pro-${{ github.event.inputs.version }}
          path: ${GITHUB_WORKSPACE}/roadmapwp-pro-${{ github.event.inputs.version }}.zip
