name: Gutenberg Market Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create temporary directory
      run: |
        mkdir temp_dir

    - name: Copy files to temporary directory, excluding specific files
      run: |
        rsync -av --exclude='.git/' --exclude='.github/' \
              --exclude='composer.json' --exclude='composer.lock' \
              --exclude='package.json' --exclude='package-lock.json' \
              --exclude='phpstan.neon' --exclude='phpstan-baseline.neon' \
              --exclude='postcss.config.js' --exclude='tailwind.config.js' \
              --exclude='gutenberg-market.php' \
              . temp_dir/
        mv temp_dir roadmapwp-pro

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: roadmapwp-pro-${{ github.event.inputs.tag }}
        path: roadmapwp-pro/
