name: Gutenberg Market Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare plugin directory
        run: |
          mkdir -p "release/roadmapwp-pro"
          rsync -av --exclude={.git,.github,composer.json,composer.lock,package.json,package-lock.json,phpstan.neon,phpstan-baseline.neon,postcss.config.js,tailwind.config.js,EDD_Licensing.php,EDD_SL_Plugin_Updater.php,gutenberg-market.php} ./ "release/roadmapwp-pro/"
          echo "Prepared plugin directory with necessary files."

      - name: Upload ZIP as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: "roadmapwp-pro-${{ github.event.inputs.version }}.zip"
          path: "release/roadmapwp-pro-${{ github.event.inputs.version }}.zip"
