name: Gutenber Market Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release for gutenberg market'
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up file structure and remove unwanted files
        run: |
          mkdir "roadmapwp-pro"
          rsync -av --exclude={.git,.github,composer.json,composer.lock,package.json,package-lock.json,phpstan.neon,phpstan-baseline.neon,postcss.config.js,tailwind.config.js,EDD_Licensing.php,EDD_SL_Plugin_Updater.php,gutenberg-market.php} ./ "roadmapwp-pro/"
          echo "Removed specified files and directories."

      - name: Package the plugin
        run: |
          zip -r "roadmapwp-pro-${{ inputs.version }}.zip" "roadmapwp-pro"
          echo "Packaged the plugin into roadmapwp-pro-${{ inputs.version }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "roadmapwp-pro-${{ github.event.inputs.version }}.zip"
          path: "roadmapwp-pro-${{ github.event.inputs.version }}.zip"

