name: Gutenberg Market Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare the plugin directory
        run: |
          mkdir release
          # Excludes specified files and directories while copying to a new directory
          rsync -av --exclude={'.git','/.github','composer.json','composer.lock','package.json','package-lock.json','phpstan.neon','phpstan-baseline.neon','postcss.config.js','tailwind.config.js','EDD_Licensing.php','EDD_SL_Plugin_Updater.php','gutenberg-market.php'} ./ release/plugin-name/

      - name: Zip the plugin folder
        run: |
          cd release
          zip -r "../plugin-name-${{ github.event.inputs.tag }}.zip" "plugin-name"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-name-${{ github.event.inputs.tag }}
          path: plugin-name-${{ github.event.inputs.tag }}.zip
