name: Gutenberg Market Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare the plugin directory
      run: |
        # Rename the working directory to match the plugin name
        mv $GITHUB_WORKSPACE "plugin-name"

        # Move the renamed plugin directory into a new directory to structure the zip file correctly
        mkdir -p release
        mv "plugin-name" release/

    - name: Exclude specific files and directories
      run: |
        # Remove specific files and directories from the plugin folder
        rm -rf release/plugin-name/.git
        rm -rf release/plugin-name/.github
        rm release/plugin-name/composer.json
        rm release/plugin-name/composer.lock
        rm release/plugin-name/package.json
        rm release/plugin-name/package-lock.json
        rm release/plugin-name/phpstan.neon
        rm release/plugin-name/phpstan-baseline.neon
        rm release/plugin-name/postcss.config.js
        rm release/plugin-name/tailwind.config.js

    - name: Zip the plugin folder
      run: |
        zip -r "plugin-name-${{ github.event.inputs.tag }}.zip" release/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin-name-${{ github.event.inputs.tag }}
        path: plugin-name-${{ github.event.inputs.tag }}.zip
