name: Gutenberg Market Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: |
        mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: |
        mv temp_dir roadmapwp-pro

    - name: Zip the folder
      run: |
        zip -r roadmapwp-pro-${{ github.event.inputs.tag }}.zip roadmapwp-pro \
        -x "*.git/*" "*.github/*" \
        "roadmapwp-pro/composer.json" "roadmapwp-pro/composer.lock" \
        "roadmapwp-pro/package.json" "roadmapwp-pro/package-lock.json" \
        "roadmapwp-pro/phpstan.neon" "roadmapwp-pro/phpstan-baseline.neon" \
        "roadmapwp-pro/postcss.config.js" "roadmapwp-pro/tailwind.config.js" \
        "roadmapwp-pro/EDD_Licensing.php" "roadmapwp-pro/EDD_SL_Plugin_Updater.php" \
        "roadmapwp-pro/.gitignore" "roadmapwp-pro/webpack.config.js" "roadmapwp-pro/src/*"

    - name: Create Pre-Release
      uses: softprops/action-gh-release@v1
      with:
        files: roadmapwp-pro-${{ github.event.inputs.tag }}.zip
        tag_name: ${{ github.event.inputs.tag }}
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
