name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag (e.g., v1.0.6)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Checkout Completion
        run: echo "Checked out code"

      - name: Install zip utility
        run: |
          sudo apt-get install zip
          echo "Installed zip utility"

      - name: Zip the repository
        run: |
          zip -r roadmapwp.zip .
          echo "Created roadmapwp.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: roadmapwp.zip
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Release Attempt
        run: echo "Attempting to create a release for tag ${{ github.event.inputs.tag }}"

permissions:
  contents: write
