name: Create Release

on:
  workflow_dispatch:
      tags:
        # release tags should start with 'v'. Example: v1.0.0
        - "v*"

jobs:
  validation:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # We always use the main branch for the release.
          ref: main

      - name: Get tag
        id: tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
