name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'  # Input field to specify the tag name
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify Node.js version 16

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive  # Optional: include this line if you need to fetch submodules

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: .
        tag_name: ${{ github.event.inputs.tag }}  # Use the input tag value
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



