name: Create Release

on:
  workflow_dispatch:
      tags:
        # release tags should start with 'v'. Example: v1.0.0
        - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip utility
      run: sudo apt-get install zip

    - name: Zip the repository
      run: zip -r release.zip .

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
