name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'  # Input field to specify the tag name
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: .
        tag_name: ${{ github.event.inputs.tag }}  # Use the input tag value
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
