name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'  # Input field to specify the tag name
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create temporary directory
      run: |
        mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: |
        mv temp_dir roadmapwp-pro

    - name: Zip the folder
      run: |
        zip -r roadmapwp-pro-${{ github.event.inputs.tag }}.zip roadmapwp-pro -x "*.git/*" "*.github/*"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: roadmapwp-pro-${{ github.event.inputs.tag }}.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write