name: Create Release

on:
  workflow_dispatch:
    # inputs:
    #   tag:
    #     description: 'Release Tag (e.g., v1.0.6)'
    #     required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip utility
        run: sudo apt-get install zip

      - name: Zip the repository
        run: zip -r release.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
