name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'  # Input field to specify the tag name
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create desired directory
      run: |
        mkdir wproadmap

    - name: Copy files to new directory
      run: |
        cp -r * wproadmap/

    - name: Zip the folder
      run: |
        zip -r wproadmap-${{ github.event.inputs.tag }}.zip wproadmap

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: wproadmap-${{ github.event.inputs.tag }}.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
