name: Create Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: true
        type: choice
        options:
          - main
          - develop
          # Add more branches here as options
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Install zip utility
      run: sudo apt-get install zip

    - name: Zip the repository
      run: zip -r release.zip .

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
